site_name: AIMS-Factory
repo_url: https://github.com/mads-2/AIMS-Factory

nav:
  - Home: index.md
  - Workflows:
      - AIMD:
          - Overview: workflows/aimd/overview.md
          - Molecular Dynamics (MD): workflows/aimd/md.md
          - Optimization (Opt): workflows/aimd/opt.md

